config/routes.rb
Rails.application.routes.draw do

  resources :patients
  resources :patient
  resources :treatments
  resources :problems
  resources :problemtypes
  resources :medications
  resources :appointments

  devise_for :users
  get 'pages/home', :as => "home"
  root "pages#home"

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
    belongs_to :user
    belongs_to :patient
end

app/models/client.rb
class Client < ActiveRecord::Base
end

app/models/conflict.rb
class Conflict < ActiveRecord::Base
    belongs_to :exclude
    belongs_to :medication
end

app/models/devicetype.rb
class Devicetype < ActiveRecord::Base
   has_many :phone
end

app/models/exclude.rb
class Exclude < ActiveRecord::Base
    belongs_to :medication
    has_many :conflicts
end

app/models/medication.rb
class Medication < ActiveRecord::Base
   has_many :patient_medication
   has_many :excludes
   has_many :conflicts
end

app/models/notification.rb
class Notification < ActiveRecord::Base
   belongs_to :user
end

app/models/patient.rb
class Patient < ActiveRecord::Base
   belongs_to :user
   has_many :phones
   has_many :problems
   has_many :clients
   has_many :patient_medication
   has_many :appointments
end

app/models/patient_problem.rb
class PatientProblem < ActiveRecord::Base
   belongs_to :patient
   belongs_to :problem
end

app/models/phone.rb
class Phone < ActiveRecord::Base
   belongs_to :patient
   belongs_to :devicetype
end

app/models/problem.rb
class Problem < ActiveRecord::Base
   belongs_to :patient
   belongs_to :problemtype
end

app/models/problemtype.rb
class Problemtype < ActiveRecord::Base
   has_many :problemtype_treatment
   has_many :problems
end

app/models/treatment.rb
class Treatment < ActiveRecord::Base
   has_many :problemtype_treatment
end

app/models/user.rb
class User < ActiveRecord::Base
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
	belongs_to :usertype
	has_many :patients
	has_many :clients
    has_many :appointments
    has_many :notifications
end

app/models/usertype.rb
class Usertype < ActiveRecord::Base
   has_many :users
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/problem_helper.rb
module ProblemHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
%head
    %title SiiZ | Samen inzicht in Zorg
    = favicon_link_tag 'favicon.ico'
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    %link{:rel => "stylesheet", :href => "http://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.1/normalize.min.css"}
    %link{:rel => "stylesheet", :href => "http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css"}
    = csrf_meta_tags
%body
    %header
        .wrapper.clearfix
            #logo= link_to image_tag("logo.png"), root_path
            %nav
                - if user_signed_in?
                    = link_to current_user.name, edit_user_registration_path
                    = link_to('Logout', destroy_user_session_path, :method => :delete)
                    - if current_user.usertype_id == 2
                        = link_to "new patient", new_patient_path, class: "button"
    = yield

    %footer
        %center
            = link_to image_tag("logo-footer.png"), root_path

app/views/pages/home.html.haml
#main_block_1
    %p this is the main block

#main_block_2
    %p This is the second block